package com.project.notification.enums;

public enum NotificationCode {
    USER_REQUEST_OTP,

    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    RESERVATION_CREATED,
    RESERVATION_UPDATED,
    RESERVATION_CANCELLED,

    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    WALLET_TOP_UP_SUCCEEDED,

    COMMUNITY_POST_APPLIED,
    COMMUNITY_APPLICATION_WITHDRAWN,
    COMMUNITY_APPLICATION_ACCEPTED,
    COMMUNITY_APPLICATION_REJECTED,
    COMMUNITY_OPPONENT_MATCHED,
    COMMUNITY_PLAYER_RECRUITMENT_FULL,
    COMMUNITY_POST_CLOSED,
    COMMUNITY_EVALUATION_REMINDER,
    COMMUNITY_POST_HIDDEN,
    COMMUNITY_MODERATION_WARNING,
    COMMUNITY_TEMPORARY_POSTING_BAN,
    COMMUNITY_PERMANENT_POSTING_BAN,
    COMMUNITY_APPLICATION_AUTO_REJECTED,

    FIELD_APPROVED,
    FIELD_REJECTED,
    FIELD_EMPLOYEE_ASSIGNED,

    FIELD_VIOLATION_WARNING,
    FIELD_BAN,
    FIELD_UNBAN,
    PLATFORM_BAN,
    PAYMENT_DISPUTE_SUBMITTED,
    PAYMENT_DISPUTE_APPROVED,
    PAYMENT_DISPUTE_REJECTED
}
