-- Squashed demo seed data for notification-service.
-- Generated by combining prior db/dev-migration files in Flyway version order.

-- BEGIN V2__seed_demo_notifications.sql
INSERT INTO notification (id, user_id, code, title, payload, is_read, created_at, read_at)
SELECT md5('notification-' || n)::uuid,
       CASE WHEN n % 3 = 0 THEN '20000000-0000-0000-0000-000000000001'::uuid
            ELSE ('30000000-0000-0000-0000-' || lpad(((n % 5) + 1)::text, 12, '0'))::uuid END,
       (ARRAY['BOOKING_CREATED','BOOKING_CONFIRMED','PAYMENT_SUCCESS','FIELD_APPROVED'])[1 + (n % 4)],
       (ARRAY['Yêu cầu đặt sân mới','Đặt sân đã xác nhận','Thanh toán thành công','Sân đã được duyệt'])[1 + (n % 4)],
       jsonb_build_object('demo', true, 'sequence', n), n % 3 = 0,
       NOW() - (n || ' hours')::interval,
       CASE WHEN n % 3 = 0 THEN NOW() - (n || ' hours')::interval ELSE NULL END
FROM generate_series(1, 30) AS n
ON CONFLICT (id) DO NOTHING;

-- END V2__seed_demo_notifications.sql

