server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://${eureka.instance.hostname}:${server.port}/eureka/}

spring:
  config:
    import:
      - optional:file:common/.env.properties
  application:
    name: discovery-service
  profiles:
    active: ${APP_MODE:dev}
    group:
      DEV: dev
      PROD: prod
