-- Squashed clean baseline for payment-service.
-- Generated by combining prior db/migration files in Flyway version order.

-- BEGIN V1__baseline_payment_service_schema.sql
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION vietnamese_search_normalize(input TEXT)
RETURNS TEXT
LANGUAGE SQL
IMMUTABLE
STRICT
PARALLEL SAFE
AS $$
    SELECT lower(public.unaccent('public.unaccent'::regdictionary, trim(input)))
$$;

CREATE TABLE booking_payment_projections (
    booking_id UUID PRIMARY KEY, booking_code VARCHAR(50) NOT NULL, user_id UUID NOT NULL,
    user_email VARCHAR(255), total_amount NUMERIC(19,2) NOT NULL CHECK (total_amount > 0)
);
CREATE TABLE payments (
    id UUID PRIMARY KEY, booking_id UUID NOT NULL UNIQUE, user_id UUID NOT NULL,
    provider VARCHAR(30) NOT NULL CHECK (provider IN ('STRIPE')),
    stripe_session_id VARCHAR(255) UNIQUE, payment_intent_id VARCHAR(255) UNIQUE,
    amount NUMERIC(19,2) NOT NULL CHECK (amount > 0), currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','SUCCESS','FAILED','CANCELLED')),
    failure_reason VARCHAR(500), checkout_attempt INTEGER NOT NULL DEFAULT 0, version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255), updated_by VARCHAR(255), deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_payments_user ON payments(user_id);
CREATE TABLE payment_sessions (
    provider_session_id VARCHAR(255) PRIMARY KEY, payment_id UUID NOT NULL REFERENCES payments(id), attempt INTEGER NOT NULL,
    CONSTRAINT uk_payment_session_attempt UNIQUE(payment_id, attempt)
);
CREATE TABLE provider_webhook_events (
    event_id VARCHAR(255) PRIMARY KEY, provider VARCHAR(30) NOT NULL,
    event_type VARCHAR(100) NOT NULL, processed_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE outbox_events (
    id UUID PRIMARY KEY, aggregate_type VARCHAR(255) NOT NULL, aggregate_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL, topic VARCHAR(255) NOT NULL, event_key VARCHAR(255) NOT NULL,
    payload OID NOT NULL, headers OID NOT NULL, status VARCHAR(255) NOT NULL, retry_count INTEGER NOT NULL,
    next_retry_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL, published_at TIMESTAMPTZ, error_message OID
);
CREATE INDEX idx_payment_outbox_status ON outbox_events(status);
CREATE INDEX idx_payment_outbox_next_retry ON outbox_events(next_retry_at);
CREATE INDEX idx_payment_outbox_created ON outbox_events(created_at);
CREATE TABLE inbox_events (
    id UUID PRIMARY KEY, event_id VARCHAR(255) NOT NULL, consumer_group VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL, kafka_partition INTEGER NOT NULL, kafka_offset BIGINT NOT NULL,
    payload_type VARCHAR(255) NOT NULL, payload OID NOT NULL, status VARCHAR(255) NOT NULL,
    retry_count INTEGER NOT NULL, next_retry_at TIMESTAMPTZ NOT NULL, received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ, error_message OID, CONSTRAINT uk_payment_inbox_event UNIQUE(event_id, consumer_group)
);
CREATE INDEX idx_payment_inbox_status ON inbox_events(status);
CREATE INDEX idx_payment_inbox_next_retry ON inbox_events(next_retry_at);

-- END V1__baseline_payment_service_schema.sql

-- BEGIN V2__add_payment_expiration.sql
ALTER TABLE payments ADD COLUMN expires_at TIMESTAMPTZ;

-- END V2__add_payment_expiration.sql

-- BEGIN V3__add_platform_booking_fee_projection.sql
ALTER TABLE booking_payment_projections
    ADD COLUMN IF NOT EXISTS platform_booking_fee BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sub_field_price NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS booking_price BIGINT NOT NULL DEFAULT 0;

UPDATE booking_payment_projections
SET sub_field_price = COALESCE(sub_field_price, total_amount),
    booking_price = COALESCE(NULLIF(booking_price, 0), platform_booking_fee, 0)
WHERE sub_field_price IS NULL OR booking_price = 0;

ALTER TABLE booking_payment_projections
    ALTER COLUMN sub_field_price SET NOT NULL;

ALTER TABLE booking_payment_projections
    ADD CONSTRAINT chk_booking_payment_projection_platform_booking_fee_non_negative CHECK (platform_booking_fee >= 0);

-- END V3__add_platform_booking_fee_projection.sql

-- BEGIN V4__add_booking_price_projection_columns.sql
ALTER TABLE booking_payment_projections
    ADD COLUMN IF NOT EXISTS sub_field_price NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS booking_price BIGINT NOT NULL DEFAULT 0;

UPDATE booking_payment_projections
SET sub_field_price = COALESCE(sub_field_price, total_amount),
    booking_price = COALESCE(NULLIF(booking_price, 0), platform_booking_fee, 0)
WHERE sub_field_price IS NULL OR booking_price = 0;

ALTER TABLE booking_payment_projections
    ALTER COLUMN sub_field_price SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_booking_payment_projection_booking_price_non_negative'
    ) THEN
        ALTER TABLE booking_payment_projections
            ADD CONSTRAINT chk_booking_payment_projection_booking_price_non_negative CHECK (booking_price >= 0);
    END IF;
END $$;

-- END V4__add_booking_price_projection_columns.sql

-- BEGIN V5__wallet_top_up_payments.sql
ALTER TABLE payments
    DROP CONSTRAINT IF EXISTS payments_booking_id_key;

ALTER TABLE payments
    ALTER COLUMN booking_id DROP NOT NULL;

ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS purpose VARCHAR(30) NOT NULL DEFAULT 'WALLET_TOP_UP';

ALTER TABLE payments
    DROP CONSTRAINT IF EXISTS chk_payments_purpose;

ALTER TABLE payments
    ADD CONSTRAINT chk_payments_purpose CHECK (purpose IN ('WALLET_TOP_UP'));

CREATE INDEX IF NOT EXISTS idx_payments_booking_created ON payments(booking_id, created_at DESC);

-- END V5__wallet_top_up_payments.sql

