spring:
  config:
    import: optional:file:common/.env-prod.properties
  datasource:
    url: ${PAYMENT_DB_URL}
    username: ${PAYMENT_DB_USERNAME}
    password: ${PAYMENT_DB_PASSWORD}
internal:
  gateway:
    secret: ${INTERNAL_GATEWAY_SECRET}
    enforce-secret: true
    allow-docs-without-secret: false
