-- Squashed clean baseline for user-service.
-- Generated by combining prior db/migration files in Flyway version order.

-- BEGIN V1__baseline_user_service_schema.sql
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION vietnamese_search_normalize(input TEXT)
RETURNS TEXT
LANGUAGE SQL
IMMUTABLE
STRICT
PARALLEL SAFE
AS $$
    SELECT lower(public.unaccent('public.unaccent'::regdictionary, trim(input)))
$$;

CREATE TABLE users (
    id UUID PRIMARY KEY, phone_number VARCHAR(20) UNIQUE, email VARCHAR(100) UNIQUE,
    full_name VARCHAR(100) NOT NULL, avatar_url VARCHAR(255), user_type VARCHAR(20) NOT NULL,
    social_provider VARCHAR(20), social_provider_id VARCHAR(100), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, created_by VARCHAR(255),
    updated_by VARCHAR(255), deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY, aggregate_type VARCHAR(255) NOT NULL, aggregate_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL, topic VARCHAR(255) NOT NULL, event_key VARCHAR(255) NOT NULL,
    payload OID NOT NULL, headers OID NOT NULL, status VARCHAR(255) NOT NULL, retry_count INTEGER NOT NULL,
    next_retry_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL, published_at TIMESTAMPTZ, error_message OID
);
CREATE INDEX idx_outbox_status ON outbox_events(status);
CREATE INDEX idx_outbox_next_retry_at ON outbox_events(next_retry_at);
CREATE INDEX idx_outbox_created_at ON outbox_events(created_at);

CREATE TABLE inbox_events (
    id UUID PRIMARY KEY, event_id VARCHAR(255) NOT NULL, consumer_group VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL, kafka_partition INTEGER NOT NULL, kafka_offset BIGINT NOT NULL,
    payload_type VARCHAR(255) NOT NULL, payload OID NOT NULL, status VARCHAR(255) NOT NULL,
    retry_count INTEGER NOT NULL, next_retry_at TIMESTAMPTZ NOT NULL, received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ, error_message OID,
    CONSTRAINT uk_inbox_event_consumer UNIQUE (event_id, consumer_group)
);
CREATE INDEX idx_inbox_status ON inbox_events(status);
CREATE INDEX idx_inbox_next_retry_at ON inbox_events(next_retry_at);

-- END V1__baseline_user_service_schema.sql

-- BEGIN V2__add_avatar_upload_lifecycle.sql
ALTER TABLE users ADD COLUMN avatar_public_id VARCHAR(255);
CREATE UNIQUE INDEX uk_users_avatar_public_id ON users(avatar_public_id) WHERE avatar_public_id IS NOT NULL;

CREATE TABLE issued_avatar_public_ids (
    public_id VARCHAR(255) PRIMARY KEY,
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE avatar_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    request_id UUID NOT NULL,
    public_id VARCHAR(255) NOT NULL UNIQUE,
    upload_timestamp BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMP,
    secure_url VARCHAR(500),
    asset_version BIGINT,
    image_format VARCHAR(32),
    width INTEGER,
    height INTEGER,
    byte_size BIGINT,
    CONSTRAINT uk_avatar_upload_user_request UNIQUE(user_id, request_id)
);
CREATE INDEX idx_avatar_uploads_stale ON avatar_uploads(created_at) WHERE secure_url IS NULL;

-- END V2__add_avatar_upload_lifecycle.sql

-- BEGIN V3__add_user_balance.sql
ALTER TABLE users ADD COLUMN balance BIGINT NOT NULL DEFAULT 0 CHECK (balance >= 0);

CREATE TABLE user_balance_transactions (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    booking_id UUID NOT NULL,
    operation_key VARCHAR(120) NOT NULL UNIQUE,
    type VARCHAR(30) NOT NULL,
    amount BIGINT NOT NULL CHECK (amount > 0),
    reason VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_user_balance_transactions_user ON user_balance_transactions(user_id);
CREATE INDEX idx_user_balance_transactions_booking ON user_balance_transactions(booking_id);

-- END V3__add_user_balance.sql

-- BEGIN V4__enhance_user_profiles.sql
ALTER TABLE users
    ADD COLUMN bio VARCHAR(500),
    ADD COLUMN team_photo_url VARCHAR(255),
    ADD COLUMN team_photo_public_id VARCHAR(255),
    ADD COLUMN skill_level VARCHAR(30) NOT NULL DEFAULT 'AVERAGE',
    ADD COLUMN total_matches INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN wins INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN draws INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN losses INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN no_cancel_rate NUMERIC(5,2) NOT NULL DEFAULT 100.00,
    ADD COLUMN on_time_rate NUMERIC(5,2) NOT NULL DEFAULT 100.00,
    ADD COLUMN fair_play_rate NUMERIC(5,2) NOT NULL DEFAULT 100.00;

CREATE UNIQUE INDEX uk_users_team_photo_public_id ON users(team_photo_public_id) WHERE team_photo_public_id IS NOT NULL;

-- END V4__enhance_user_profiles.sql

-- BEGIN V5__add_user_reputation_evaluations.sql
CREATE TABLE user_reputation_evaluations (
    id UUID PRIMARY KEY,
    post_id UUID NOT NULL,
    booking_id UUID NOT NULL,
    evaluator_id UUID NOT NULL,
    evaluated_user_id UUID NOT NULL REFERENCES users(id),
    arrived_on_time BOOLEAN NOT NULL,
    cancelled_unexpectedly BOOLEAN NOT NULL,
    fair_play BOOLEAN NOT NULL,
    would_play_again BOOLEAN NOT NULL,
    comment VARCHAR(1000),
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_user_reputation_evaluations_user ON user_reputation_evaluations(evaluated_user_id);

-- END V5__add_user_reputation_evaluations.sql

-- BEGIN V6__add_completed_booking_count_and_platform_ban.sql
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS completed_booking_count INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);

-- END V6__add_completed_booking_count_and_platform_ban.sql

-- BEGIN V7__allow_wallet_top_up_transactions.sql
ALTER TABLE user_balance_transactions
    ALTER COLUMN booking_id DROP NOT NULL;

-- END V7__allow_wallet_top_up_transactions.sql

