ALTER TABLE users ADD COLUMN avatar_public_id VARCHAR(255);
CREATE UNIQUE INDEX uk_users_avatar_public_id ON users(avatar_public_id) WHERE avatar_public_id IS NOT NULL;

CREATE TABLE issued_avatar_public_ids (
    public_id VARCHAR(255) PRIMARY KEY,
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE avatar_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    request_id UUID NOT NULL,
    public_id VARCHAR(255) NOT NULL UNIQUE,
    upload_timestamp BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMP,
    secure_url VARCHAR(500),
    asset_version BIGINT,
    image_format VARCHAR(32),
    width INTEGER,
    height INTEGER,
    byte_size BIGINT,
    CONSTRAINT uk_avatar_upload_user_request UNIQUE(user_id, request_id)
);
CREATE INDEX idx_avatar_uploads_stale ON avatar_uploads(created_at) WHERE secure_url IS NULL;
