ALTER TABLE users
    ADD COLUMN bio VARCHAR(500),
    ADD COLUMN team_photo_url VARCHAR(255),
    ADD COLUMN team_photo_public_id VARCHAR(255),
    ADD COLUMN skill_level VARCHAR(30) NOT NULL DEFAULT 'AVERAGE',
    ADD COLUMN total_matches INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN wins INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN draws INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN losses INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN no_cancel_rate NUMERIC(5,2) NOT NULL DEFAULT 100.00,
    ADD COLUMN on_time_rate NUMERIC(5,2) NOT NULL DEFAULT 100.00,
    ADD COLUMN fair_play_rate NUMERIC(5,2) NOT NULL DEFAULT 100.00;

CREATE UNIQUE INDEX uk_users_team_photo_public_id ON users(team_photo_public_id) WHERE team_photo_public_id IS NOT NULL;
