CREATE TABLE fields (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    address VARCHAR(255) NOT NULL,
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    phone_number VARCHAR(20) NOT NULL,
    email VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    rating_average NUMERIC(3, 2) DEFAULT 0,
    total_reviews INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE field_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_type VARCHAR(30) NOT NULL UNIQUE,
    default_booking_duration_minutes INTEGER NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE field_field_types (
    field_id UUID NOT NULL REFERENCES fields(id),
    field_type_id BIGINT NOT NULL REFERENCES field_types(id),
    PRIMARY KEY (field_id, field_type_id)
);

CREATE TABLE sub_fields (
    id UUID PRIMARY KEY,
    field_id UUID NOT NULL REFERENCES fields(id),
    name VARCHAR(100) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    indoor_outdoor VARCHAR(20),
    surface_type VARCHAR(50),
    sub_field_type VARCHAR(50) NOT NULL,
    changing_room BOOLEAN NOT NULL DEFAULT FALSE,
    shower BOOLEAN NOT NULL DEFAULT FALSE,
    wifi BOOLEAN NOT NULL DEFAULT FALSE,
    air_conditioning BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE field_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id UUID NOT NULL REFERENCES fields(id),
    image_url VARCHAR(500) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE reviews (
    id UUID PRIMARY KEY,
    field_id UUID NOT NULL REFERENCES fields(id),
    user_id UUID NOT NULL,
    rating INTEGER NOT NULL,
    comment TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE booking_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_field_id UUID NOT NULL UNIQUE REFERENCES sub_fields(id),
    minimum_booking_duration_minutes INTEGER,
    maximum_booking_duration_minutes INTEGER,
    booking_interval_minutes INTEGER
);

CREATE TABLE time_price_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_field_id UUID NOT NULL REFERENCES sub_fields(id),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    hourly_price NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE field_operating_hours (
    id UUID PRIMARY KEY,
    field_id UUID NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    open_time TIME,
    close_time TIME,
    closed BOOLEAN NOT NULL,
    CONSTRAINT uk_field_hours_day UNIQUE (field_id, day_of_week)
);

CREATE TABLE sub_field_operating_hours (
    id UUID PRIMARY KEY,
    sub_field_id UUID NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    open_time TIME,
    close_time TIME,
    closed BOOLEAN NOT NULL,
    CONSTRAINT uk_sub_field_hours_day UNIQUE (sub_field_id, day_of_week)
);

CREATE TABLE sub_field_closures (
    id UUID PRIMARY KEY,
    sub_field_id UUID NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR(255)
);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    event_key VARCHAR(255) NOT NULL,
    payload OID NOT NULL,
    headers OID NOT NULL,
    status VARCHAR(255) NOT NULL,
    retry_count INTEGER NOT NULL,
    next_retry_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    error_message OID
);

CREATE INDEX idx_outbox_status ON outbox_events(status);
CREATE INDEX idx_outbox_next_retry_at ON outbox_events(next_retry_at);
CREATE INDEX idx_outbox_created_at ON outbox_events(created_at);

CREATE TABLE inbox_events (
    id UUID PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    consumer_group VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    kafka_partition INTEGER NOT NULL,
    kafka_offset BIGINT NOT NULL,
    payload_type VARCHAR(255) NOT NULL,
    payload OID NOT NULL,
    status VARCHAR(255) NOT NULL,
    retry_count INTEGER NOT NULL,
    next_retry_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ,
    error_message OID,
    CONSTRAINT uk_inbox_event_consumer UNIQUE (event_id, consumer_group)
);

CREATE INDEX idx_inbox_status ON inbox_events(status);
CREATE INDEX idx_inbox_next_retry_at ON inbox_events(next_retry_at);

CREATE INDEX idx_fields_owner ON fields(owner_id);
CREATE INDEX idx_fields_status_active ON fields(status, active);
CREATE INDEX idx_sub_fields_field ON sub_fields(field_id);
CREATE INDEX idx_reviews_field ON reviews(field_id);
