-- Squashed clean baseline for field-service.
-- Generated by combining prior db/migration files in Flyway version order.

-- BEGIN V1__baseline_field_service_schema.sql
CREATE TABLE fields (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    address VARCHAR(255) NOT NULL,
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    phone_number VARCHAR(20) NOT NULL,
    email VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    rating_average NUMERIC(3, 2) DEFAULT 0,
    total_reviews INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE field_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_type VARCHAR(30) NOT NULL UNIQUE,
    default_booking_duration_minutes INTEGER NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE field_field_types (
    field_id UUID NOT NULL REFERENCES fields(id),
    field_type_id BIGINT NOT NULL REFERENCES field_types(id),
    PRIMARY KEY (field_id, field_type_id)
);

CREATE TABLE sub_fields (
    id UUID PRIMARY KEY,
    field_id UUID NOT NULL REFERENCES fields(id),
    name VARCHAR(100) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    indoor_outdoor VARCHAR(20),
    surface_type VARCHAR(50),
    sub_field_type VARCHAR(50) NOT NULL,
    changing_room BOOLEAN NOT NULL DEFAULT FALSE,
    shower BOOLEAN NOT NULL DEFAULT FALSE,
    wifi BOOLEAN NOT NULL DEFAULT FALSE,
    air_conditioning BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE field_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id UUID NOT NULL REFERENCES fields(id),
    image_url VARCHAR(500) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE reviews (
    id UUID PRIMARY KEY,
    field_id UUID NOT NULL REFERENCES fields(id),
    user_id UUID NOT NULL,
    rating INTEGER NOT NULL,
    comment TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE booking_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_field_id UUID NOT NULL UNIQUE REFERENCES sub_fields(id),
    minimum_booking_duration_minutes INTEGER,
    maximum_booking_duration_minutes INTEGER,
    booking_interval_minutes INTEGER
);

CREATE TABLE time_price_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_field_id UUID NOT NULL REFERENCES sub_fields(id),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    hourly_price NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE field_operating_hours (
    id UUID PRIMARY KEY,
    field_id UUID NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    open_time TIME,
    close_time TIME,
    closed BOOLEAN NOT NULL,
    CONSTRAINT uk_field_hours_day UNIQUE (field_id, day_of_week)
);

CREATE TABLE sub_field_operating_hours (
    id UUID PRIMARY KEY,
    sub_field_id UUID NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    open_time TIME,
    close_time TIME,
    closed BOOLEAN NOT NULL,
    CONSTRAINT uk_sub_field_hours_day UNIQUE (sub_field_id, day_of_week)
);

CREATE TABLE sub_field_closures (
    id UUID PRIMARY KEY,
    sub_field_id UUID NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR(255)
);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    event_key VARCHAR(255) NOT NULL,
    payload OID NOT NULL,
    headers OID NOT NULL,
    status VARCHAR(255) NOT NULL,
    retry_count INTEGER NOT NULL,
    next_retry_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    error_message OID
);

CREATE INDEX idx_outbox_status ON outbox_events(status);
CREATE INDEX idx_outbox_next_retry_at ON outbox_events(next_retry_at);
CREATE INDEX idx_outbox_created_at ON outbox_events(created_at);

CREATE TABLE inbox_events (
    id UUID PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    consumer_group VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    kafka_partition INTEGER NOT NULL,
    kafka_offset BIGINT NOT NULL,
    payload_type VARCHAR(255) NOT NULL,
    payload OID NOT NULL,
    status VARCHAR(255) NOT NULL,
    retry_count INTEGER NOT NULL,
    next_retry_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ,
    error_message OID,
    CONSTRAINT uk_inbox_event_consumer UNIQUE (event_id, consumer_group)
);

CREATE INDEX idx_inbox_status ON inbox_events(status);
CREATE INDEX idx_inbox_next_retry_at ON inbox_events(next_retry_at);

CREATE INDEX idx_fields_owner ON fields(owner_id);
CREATE INDEX idx_fields_status_active ON fields(status, active);
CREATE INDEX idx_sub_fields_field ON sub_fields(field_id);
CREATE INDEX idx_reviews_field ON reviews(field_id);

-- END V1__baseline_field_service_schema.sql

-- BEGIN V2__add_legacy_and_v3_field_locations.sql
ALTER TABLE fields
    ADD COLUMN IF NOT EXISTS ward VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ward_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS province VARCHAR(255),
    ADD COLUMN IF NOT EXISTS province_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS legacy_ward VARCHAR(255),
    ADD COLUMN IF NOT EXISTS legacy_ward_code VARCHAR(20),
    ADD COLUMN IF NOT EXISTS legacy_district VARCHAR(255),
    ADD COLUMN IF NOT EXISTS legacy_province VARCHAR(255);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'fields'
          AND column_name = 'district'
    ) THEN
        EXECUTE 'UPDATE fields SET legacy_district = COALESCE(legacy_district, district)';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'fields'
          AND column_name = 'city'
    ) THEN
        EXECUTE 'UPDATE fields SET legacy_province = COALESCE(legacy_province, city)';
    END IF;
END $$;

UPDATE fields
SET legacy_ward = COALESCE(legacy_ward, ward, 'Chưa cập nhật'),
    legacy_ward_code = COALESCE(legacy_ward_code, ward_code, 'UNKNOWN'),
    legacy_district = COALESCE(legacy_district, 'Chưa cập nhật'),
    legacy_province = COALESCE(legacy_province, province, 'Chưa cập nhật'),
    ward = COALESCE(ward, legacy_ward, 'Chưa cập nhật'),
    ward_code = COALESCE(ward_code, legacy_ward_code, 'UNKNOWN'),
    province = COALESCE(province, legacy_province, 'Chưa cập nhật'),
    province_code = COALESCE(province_code, 'UNKNOWN'),
    latitude = COALESCE(latitude, 0),
    longitude = COALESCE(longitude, 0);

ALTER TABLE fields
    ALTER COLUMN ward SET NOT NULL,
    ALTER COLUMN ward_code SET NOT NULL,
    ALTER COLUMN province SET NOT NULL,
    ALTER COLUMN province_code SET NOT NULL,
    ALTER COLUMN legacy_ward SET NOT NULL,
    ALTER COLUMN legacy_ward_code SET NOT NULL,
    ALTER COLUMN legacy_district SET NOT NULL,
    ALTER COLUMN legacy_province SET NOT NULL,
    ALTER COLUMN latitude SET NOT NULL,
    ALTER COLUMN longitude SET NOT NULL;

ALTER TABLE fields DROP COLUMN IF EXISTS district;
ALTER TABLE fields DROP COLUMN IF EXISTS city;

CREATE INDEX IF NOT EXISTS idx_fields_province_code ON fields(province_code);
CREATE INDEX IF NOT EXISTS idx_fields_ward_code ON fields(ward_code);
CREATE INDEX IF NOT EXISTS idx_fields_legacy_ward_code ON fields(legacy_ward_code);

-- END V2__add_legacy_and_v3_field_locations.sql

-- BEGIN V3__optimize_field_card_search.sql
CREATE INDEX IF NOT EXISTS idx_fields_public_rating
    ON fields (rating_average DESC, id) WHERE status = 'APPROVED' AND active = true AND deleted = false;

CREATE INDEX IF NOT EXISTS idx_fields_public_reviews
    ON fields (total_reviews DESC, id) WHERE status = 'APPROVED' AND active = true AND deleted = false;

CREATE INDEX IF NOT EXISTS idx_fields_public_location
    ON fields (province_code, ward_code) WHERE status = 'APPROVED' AND active = true AND deleted = false;

CREATE INDEX IF NOT EXISTS idx_field_images_primary
    ON field_images (field_id, is_primary DESC, display_order, id);

CREATE INDEX IF NOT EXISTS idx_sub_fields_search_type
    ON sub_fields (sub_field_type, field_id) WHERE active = true AND deleted = false;

CREATE INDEX IF NOT EXISTS idx_field_field_types_reverse
    ON field_field_types (field_type_id, field_id);

-- END V3__optimize_field_card_search.sql

-- BEGIN V4__index_legacy_field_locations.sql
CREATE INDEX IF NOT EXISTS idx_fields_public_legacy_location
    ON fields (legacy_province, legacy_district)
    WHERE status = 'APPROVED' AND active = true AND deleted = false;

-- END V4__index_legacy_field_locations.sql

-- BEGIN V5__add_vietnamese_text_search.sql
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- PostgreSQL marks unaccent as STABLE. This immutable wrapper allows the same
-- normalization expression to be indexed and used safely by search queries.
CREATE OR REPLACE FUNCTION vietnamese_search_normalize(input TEXT)
RETURNS TEXT
LANGUAGE SQL
IMMUTABLE
STRICT
PARALLEL SAFE
AS $$
    SELECT lower(public.unaccent('public.unaccent'::regdictionary, trim(input)))
$$;

DROP INDEX IF EXISTS idx_fields_public_legacy_location;

CREATE INDEX IF NOT EXISTS idx_fields_public_legacy_location_normalized
    ON fields (
        vietnamese_search_normalize(legacy_province),
        vietnamese_search_normalize(legacy_district)
    )
    WHERE status = 'APPROVED' AND active = true AND deleted = false;

CREATE INDEX IF NOT EXISTS idx_fields_public_name_vietnamese_search
    ON fields USING GIN (vietnamese_search_normalize(name) gin_trgm_ops)
    WHERE status = 'APPROVED' AND active = true AND deleted = false;

CREATE INDEX IF NOT EXISTS idx_fields_public_address_vietnamese_search
    ON fields USING GIN (vietnamese_search_normalize(address) gin_trgm_ops)
    WHERE status = 'APPROVED' AND active = true AND deleted = false;

-- END V5__add_vietnamese_text_search.sql

-- BEGIN V6__add_direct_image_upload_lifecycle.sql
ALTER TABLE field_images ALTER COLUMN image_url DROP NOT NULL;
ALTER TABLE field_images ADD COLUMN public_id VARCHAR(255);
ALTER TABLE field_images ADD COLUMN upload_owner_id UUID;
ALTER TABLE field_images ADD COLUMN upload_request_id UUID;
ALTER TABLE field_images ADD COLUMN upload_slot_index INTEGER;
ALTER TABLE field_images ADD COLUMN upload_timestamp BIGINT;
ALTER TABLE field_images ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE field_images ADD COLUMN confirmed_at TIMESTAMP;
ALTER TABLE field_images ADD COLUMN asset_version BIGINT;
ALTER TABLE field_images ADD COLUMN image_format VARCHAR(32);
ALTER TABLE field_images ADD COLUMN width INTEGER;
ALTER TABLE field_images ADD COLUMN height INTEGER;
ALTER TABLE field_images ADD COLUMN byte_size BIGINT;

CREATE TABLE issued_image_public_ids (
    public_id VARCHAR(255) PRIMARY KEY,
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_field_images_public_id ON field_images(public_id) WHERE public_id IS NOT NULL;
CREATE UNIQUE INDEX uk_field_images_upload_request_slot
    ON field_images(field_id, upload_owner_id, upload_request_id, upload_slot_index)
    WHERE upload_request_id IS NOT NULL;
CREATE INDEX idx_field_images_stale_placeholder ON field_images(created_at) WHERE image_url IS NULL;

-- END V6__add_direct_image_upload_lifecycle.sql

-- BEGIN V7__remove_issued_image_public_ids.sql
DROP TABLE IF EXISTS issued_image_public_ids;

-- END V7__remove_issued_image_public_ids.sql

-- BEGIN V8__add_field_favorites.sql
CREATE TABLE field_favorites (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    field_id UUID NOT NULL REFERENCES fields(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_field_favorites_user_field UNIQUE (user_id, field_id)
);

CREATE INDEX idx_field_favorites_user ON field_favorites(user_id);
CREATE INDEX idx_field_favorites_field ON field_favorites(field_id);
CREATE INDEX idx_field_favorites_user_field_active ON field_favorites(user_id, field_id) WHERE deleted = false;

-- END V8__add_field_favorites.sql

-- BEGIN V9__add_open_24_hours_to_operating_hours.sql
ALTER TABLE field_operating_hours
    ADD COLUMN IF NOT EXISTS open_24_hours BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sub_field_operating_hours
    ADD COLUMN IF NOT EXISTS open_24_hours BOOLEAN NOT NULL DEFAULT FALSE;

-- END V9__add_open_24_hours_to_operating_hours.sql

